apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "zipkin.fullname" . }}-config
  labels:
    {{- include "zipkin.labels" . | nindent 4 }}
data:
  # Zipkin configuration (minimal)
  zipkin.yml: |
    zipkin:
      storage:
        type: mem
      collector:
        http:
          enabled: true
        kafka:
          enabled: false
        rabbitmq:
          enabled: false
