# Staging environment specific values
global:
  environment: stage
  imagePullPolicy: IfNotPresent
  imageTag: latest
  
ingress:
  enabled: true
  hosts:
    - host: ecommerce-stage.local
      paths:
        - path: /
          pathType: Prefix
          backend:
            service:
              name: api-gateway
              port:
                number: 8222

# Service specific overrides for stage environment
zipkin:
  replicaCount: 1
  resources:
    requests:
      cpu: 200m
      memory: 384Mi
    limits:
      cpu: 700m
      memory: 768Mi
      
service-discovery:
  replicaCount: 2
  resources:
    requests:
      cpu: 200m
      memory: 384Mi
    limits:
      cpu: 700m
      memory: 768Mi
      
cloud-config:
  replicaCount: 2
  resources:
    requests:
      cpu: 200m
      memory: 384Mi
    limits:
      cpu: 700m
      memory: 768Mi
      
api-gateway:
  replicaCount: 2
  resources:
    requests:
      cpu: 200m
      memory: 384Mi
    limits:
      cpu: 700m
      memory: 768Mi
      
order-service:
  replicaCount: 2
  
payment-service:
  replicaCount: 2
  
product-service:
  replicaCount: 2
  
shipping-service:
  replicaCount: 2
  
user-service:
  replicaCount: 2
  
favourite-service:
  replicaCount: 2
  
proxy-client:
  replicaCount: 2
